### ISSUE TITLE
Getting started with Keycloak/Apricot

### ISSUE THREAD

**Issue by tamama-plb** [alan-turing-institute/apricot#54]
Greetings,

I use apricot release 0.0.7

I use docker compose
Here is my env:

```
DEBUG=true

PORT=2389
BACKEND="Keycloak"

KEYCLOAK_BASE_URL="https://auth.tamama.io"
KEYCLOAK_REALM="robo-tamama"

CLIENT_ID="app--apricot"
CLIENT_SECRET="0123456789abcdef"

DOMAIN="dc=tamama,dc=io"
```

Ultimate goal - somthing like this: 

`uid=tamama,ou=users,dc=tamama,dc=io`
`gid=role-admin,ou=groups,dc=tamama,dc=io`

However, when I do smoke test:

```
[tamama@tamama-1 robo-tamama-kernel-security-keycloak]$ ldapsearch -H ldap://172.21.1.1:2389 -D uid=tamama -b dc=tamama,dc=io
ldap_bind: Protocol error (2)
        additional info: LDAP bind request failed. Expecting value: line 1 column 1 (char 0)
[tamama@tamama-1 robo-tamama-kernel-security-keycloak]$ 
```

Any quick advise or getting-started guide on this?

Thank you in advance.

----------

+ I confirm that the Keycloak backend is working OK with:

```
POST https://auth.tamama.io/realms/robo-tamama/protocol/openid-connect/token
{
      "grant_type": "client_credentials",
      "client_id": "app--apricot",
      "client_secret": "xxxxxxxxx"
}

returns me the right access token.

I can share with you the `client_secret` over DM of course...

**Comment by jemrobinson** [comment]
Can you post the output from the `apricot` server? I don't think the output from ldapsearch will be enough to debug this.

**Comment by tamama-plb** [comment]
Sure thing.

Cmd:
```
[tamama@tamama-1 robo-tamama-kernel-security-keycloak]$ ldapsearch -H ldap://172.21.1.1:2389 -D uid=tamama -b dc=tamama,dc=io
ldap_bind: Protocol error (2)
        additional info: LDAP bind request failed. Expecting value: line 1 column 1 (char 0)
[tamama@tamama-1 robo-tamama-kernel-security-keycloak]$ 
```


Debug log from Apricot:

```
robo-tamama-kernel-security-keycloak-node-1-_robo_tamama_kernel_security_keycloak_apricot-1  | 2024-11-05 20:56:38+0000 [-] Log opened.
robo-tamama-kernel-security-keycloak-node-1-_robo_tamama_kernel_security_keycloak_apricot-1  | 2024-11-05 20:56:38+0000 [-] Using a local user-id cache.
robo-tamama-kernel-security-keycloak-node-1-_robo_tamama_kernel_security_keycloak_apricot-1  | 2024-11-05 20:56:38+0000 [-] Creating an OAuthClient for OAuthBackend.KEYCLOAK.
robo-tamama-kernel-security-keycloak-node-1-_robo_tamama_kernel_security_keycloak_apricot-1  | 2024-11-05 20:56:38+0000 [-] Initialising application credential client.
robo-tamama-kernel-security-keycloak-node-1-_robo_tamama_kernel_security_keycloak_apricot-1  | 2024-11-05 20:56:38+0000 [-] Initialising delegated credential client.
robo-tamama-kernel-security-keycloak-node-1-_robo_tamama_kernel_security_keycloak_apricot-1  | 2024-11-05 20:56:38+0000 [-] Creating an LDAPServerFactory.
robo-tamama-kernel-security-keycloak-node-1-_robo_tamama_kernel_security_keycloak_apricot-1  | 2024-11-05 20:56:38+0000 [-] Attaching a listening endpoint (plain).
robo-tamama-kernel-security-keycloak-node-1-_robo_tamama_kernel_security_keycloak_apricot-1  | 2024-11-05 20:56:38+0000 [-] OAuthLDAPServerFactory starting on 2389
robo-tamama-kernel-security-keycloak-node-1-_robo_tamama_kernel_security_keycloak_apricot-1  | 2024-11-05 20:56:38+0000 [-] Starting factory OAuthLDAPServerFactory using adaptor OAuthLDAPTree with backend KeycloakClient
robo-tamama-kernel-security-keycloak-node-1-_robo_tamama_kernel_security_keycloak_apricot-1  | 2024-11-05 20:56:38+0000 [-] Starting the Twisted reactor.

robo-tamama-kernel-security-keycloak-node-1-_robo_tamama_kernel_security_keycloak_apricot-1  | 2024-11-05 20:57:43+0000 [ReadOnlyLDAPServer,0,172.21.1.1] S<-C LDAPMessage(id=1, value=LDAPBindRequest(version=3, dn=b'uid=tamama', auth='', sasl=False), controls=None)
robo-tamama-kernel-security-keycloak-node-1-_robo_tamama_kernel_security_keycloak_apricot-1  | 2024-11-05 20:57:43+0000 [ReadOnlyLDAPServer,0,172.21.1.1] Handling an LDAP bind request.
robo-tamama-kernel-security-keycloak-node-1-_robo_tamama_kernel_security_keycloak_apricot-1  | 2024-11-05 20:57:43+0000 [ReadOnlyLDAPServer,0,172.21.1.1] Starting an LDAP lookup for 'uid=tamama'.
robo-tamama-kernel-security-keycloak-node-1-_robo_tamama_kernel_security_keycloak_apricot-1  | 2024-11-05 20:57:43+0000 [ReadOnlyLDAPServer,0,172.21.1.1] Retrieving OAuth data.
robo-tamama-kernel-security-keycloak-node-1-_robo_tamama_kernel_security_keycloak_apricot-1  | 2024-11-05 20:57:43+0000 [ReadOnlyLDAPServer,0,172.21.1.1] Requesting a new authentication token from the OAuth backend.
robo-tamama-kernel-security-keycloak-node-1-_robo_tamama_kernel_security_keycloak_apricot-1  | 2024-11-05 20:57:44+0000 [ReadOnlyLDAPServer,0,172.21.1.1] S->C LDAPMessage(id=1, value=LDAPBindResponse(resultCode=2, errorMessage='LDAP bind request failed. Expecting value: line 1 column 1 (char 0)'), controls=None)
robo-tamama-kernel-security-keycloak-node-1-_robo_tamama_kernel_security_keycloak_apricot-1  | 2024-11-05 20:57:44+0000 [ReadOnlyLDAPServer,0,172.21.1.1] S<-C LDAPMessage(id=2, value=LDAPUnbindRequest(), controls=None)
robo-tamama-kernel-security-keycloak-node-1-_robo_tamama_kernel_security_keycloak_apricot-1  | 2024-11-05 20:57:44+0000 [ReadOnlyLDAPServer,0,172.21.1.1] Handling an LDAP unbind request.
```

**Comment by tamama-plb** [comment]
@jemrobinson Please do not hesitate to ask me for further details to help in your debugging. Thank you!

**Comment by jemrobinson** [comment]
@tamama-plb : Thanks - I'm a bit busy at the moment but I'll come back to this. I'll probably have to make a separate Docker container release for this (with a bit more debug info) and I'll let you now when that's done.

**Comment by jemrobinson** [comment]
@tamama-plb : Did you find a fix for this? Sorry, I haven't had time to look into it yet.

**Comment by tamama-plb** [comment]
@jemrobinson No worries, I found an alternative solution for the time being (i.e. Keycloak -> Authentik -> LDAP). No rush, I would be happy to help test your new patch whenever you are ready.
:)

**Comment by seang96** [comment]
I noticed today I am getting this same issue. I believe it has something to do with Keycloaks updates since keycloak integration was added. Since this broke without updating it.

**Comment by seang96** [comment]
I am using the keycloak operator which is easy to install if you have a Kubernetes setup already... You could probably do a single VM with k3s or talos though?

**Comment by jemrobinson** [comment]
I don't currently have a K8s environment, but I'm happy to set one up. Can you generate a minimal-reproducing example of this problem?

**Comment by seang96** [comment]
A potentially easier option on both sides, if I create a keycloak realm and some test users and groups and send you client details privately so you can test with it against apricot?

**Comment by seang96** [comment]
For Kubernetes here is easiest way IMO after installing keycloak

1. Install [Postgres operator](https://operatorhub.io/operator/cloudnative-pg)
2. Install [ingress-nginx with helm](https://github.com/kubernetes/ingress-nginx/tree/main/charts/ingress-nginx)
3. Install [cert-manager with helm](https://cert-manager.io/docs/installation/helm/)
4. Install keycloak using below. May need to run in order and wait for stuff to start to proceed with next set of resources.

You may not need cert manager or ingress if you use kubectl port-forward on service to configure keycloak, but probably need https for it to work with apricot properly?

```
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: operatorgroup
  namespace: keycloak
spec:
  targetNamespaces:
    - keycloak

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: keycloak-operator
  namespace: keycloak
spec:
  channel: fast
  name: keycloak-operator
  source: operatorhubio-catalog
  sourceNamespace: olm
```

```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: keycloak
spec:
  instances: 1
  bootstrap:
    initdb:
      database: app
      owner: app
      encoding: "UTF8"
  storage:
    size: 25Gi
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4
  postgresql:
    parameters:
      logging_collector: "on"
      max_wal_size: "2GB"
      shared_buffers: "256MB"
      wal_compression: "on"
  resources:
    requests:
      cpu: 100m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 1Gi
```

```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-keycloak
  namespace: keycloak
spec:
  secretName: cert-keycloak
  dnsNames:
    - keycloak.example.com
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io

```

```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  instances: 1
  db:
    vendor: postgres
    host: postgres-rw
    database: app
    usernameSecret:
      name: postgres-app
      key: user
    passwordSecret:
      name: postgres-app
      key: password
  http:
    httpEnabled: true
    tlsSecret: cert-keycloak
  ingress:
    enabled: false
  hostname:
    hostname: keycloak.example.com
  proxy:
    headers: xforwarded # double check your reverse proxy sets and overwrites the X-Forwarded-* headers
  unsupported:
    podTemplate:
      spec:
        containers:
          - env:
              - name: TZ
                value: America/New_York
```

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  namespace: keycloak
spec:
  tls:
    - secretName: cert-keycloak
      hosts:
        - keycloak.example.com
  rules:
    - host: keycloak.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak-service
                port:
                  number: 8080
```
